GET http://localhost:3000/movies/
###

GET http://localhost:3000/movies/12/
###

PUT http://localhost:3000/movies/12/

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###

DELETE http://localhost:3000/movies/12/
###

GET http://localhost:3000/directors/
###

GET http://localhost:3000/directors/1/Captain Marvel